Complete test cases

diff --git a/cmd/funl-exec b/cmd/funl-exec
--- a/cmd/funl-exec
+++ b/cmd/funl-exec
@@ -2,8 +2,7 @@
 
 path_remove() {
   local paths=$PATH
-  while [[ 0 -lt $# ]]
-  do
+  while [[ 0 -lt $# ]]; do
     paths=$(echo -n $paths | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//')
     shift
   done
@@ -23,7 +22,10 @@ fi
 
 new_path=$(path_remove "$bin_dir" "$FUNL_HOOKS")
 
-# echo "EXEC: $#: $@"
-# echo "EXEC: $1 | $2 | $3 | $4 | $5 | $6"
+PATH=$new_path type "$@" >/dev/null 2>&1
+if [[ 0 -ne $? ]]; then
+  echo "funl: command not found: $1" >&2
+  exit 1
+fi
 
 PATH=$new_path exec "$@"
diff --git a/cmd/funl-proc b/cmd/funl-proc
--- a/cmd/funl-proc
+++ b/cmd/funl-proc
@@ -14,16 +14,13 @@ for param in "$@"; do
     params[$i]="$param"
   else
     choice=$(funl select "$name")
-
     if [[ 0 -ne $? ]]; then
-      echo "funl: not selected, abort" >&2
       exit 1
     fi
 
     choice=$(funl post-proc "$name" "$choice")
-
     if [[ 0 -ne $? ]]; then
-      echo "funl: error occured in post-processing" >&2
+      echo "funl: error occured in post-process '$name.post'" >&2
       exit 1
     fi
 
