Define 'funl' shell function to reflect hooked commands to current shell

diff --git a/cmd/funl-feed b/cmd/funl-feed
--- a/cmd/funl-feed
+++ b/cmd/funl-feed
@@ -22,7 +22,6 @@ undef_func() {
   echo "unset -f \"$1\" >/dev/null 2>&1 || true"
 }
 
-shift
 if [[ 0 -eq $# ]]; then
   [[ -n $FUNL_DEBUG ]] && echo "funl-feed: no arguments" >&2
   exit 1
@@ -34,20 +33,20 @@ fi
 
 cmd="$1"
 case "$cmd" in
-def | undef )
-  if [[ -z $2 ]]; then
-    names=$(enum_hooks)
-  else
-    shift
-    names="$@"
-  fi
+  def | undef )
+    if [[ -z $2 ]]; then
+      names=$(enum_hooks)
+    else
+      shift
+      names="$@"
+    fi
 
-  for name in $names; do
-    echo -e "$(eval \"${cmd}_func\" \"$name\")"
-  done
-  ;;
-* )
-  [[ -n $FUNL_DEBUG ]] && echo "funl-feed: invalid subcommand: $1" >&2
-  exit 1
-  ;;
+    for name in $names; do
+      echo -e "$(eval \"${cmd}_func\" \"$name\")"
+    done
+    ;;
+  * )
+    [[ -n $FUNL_DEBUG ]] && echo "funl-feed: invalid subcommand: $1" >&2
+    exit 1
+    ;;
 esac
diff --git a/cmd/funl-init b/cmd/funl-init
--- a/cmd/funl-init
+++ b/cmd/funl-init
@@ -8,6 +8,35 @@ if [[ ! -d $FUNL_HOOKS ]]; then
   command mkdir -p "$FUNL_HOOKS"
 fi
 
+# NOTE: Separate declaration and assignment of 'output' variable
+#       to avoid problem that '\$?' always return 0 even if exit code is 1.
+
+cat <<SH
+#!/usr/bin/env bash
+
+funl() {
+  local funl_path="$FUNL_ROOT/bin/funl"
+  case "\$1" in
+    hook | unhook )
+      local cmd="\$1"
+      shift
+      local output
+      output="\$(\$funl_path \$cmd -e "\$@" 2>&1)"
+      local code="\$?"
+      if [[ 0 -eq \$code ]]; then
+        eval "\$output"
+      else
+        echo -e "\$output" >&2
+      fi
+      return \$code
+      ;;
+    * )
+      \$funl_path "\$@"
+      ;;
+  esac
+}
+SH
+
 funcs="$(funl feed def)"
 if [[ ! -z $funcs ]]; then
   echo -e "$funcs"
diff --git a/cmd/funl-post-proc b/cmd/funl-post-proc
--- a/cmd/funl-post-proc
+++ b/cmd/funl-post-proc
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
-shift
 if [[ 2 -ne $# ]]; then
+  [[ -n $FUNL_DEBUG ]] && echo "funl-post-proc: no arguments" >&2
   exit 1
 fi
 
 post=$(funl config "$1" "post")
 if [[ 0 -ne $? ]]; then
+  [[ -n $FUNL_DEBUG ]] && echo "funl-post-proc: failed in funl-config: $1: $post" >&2
   exit 1
 fi
 
@@ -17,6 +18,7 @@ fi
 
 processed=$(eval "echo \"$2\" | $post" 2>&1)
 if [[ 0 -ne $? ]]; then
+  [[ -n $FUNL_DEBUG ]] && echo "funl-post-proc: failed in post-proc: $processed" >&2
   exit 1
 fi
 
diff --git a/cmd/funl-select b/cmd/funl-select
--- a/cmd/funl-select
+++ b/cmd/funl-select
@@ -1,18 +1,20 @@
 #!/usr/bin/env bash
 
-shift
 if [[ 1 -ne $# ]]; then
+  [[ -n $FUNL_DEBUG ]] && echo "funl-select: no arguments" >&2
   exit 1
 fi
 
 src=$(funl config "$1" "src")
 if [[ 0 -ne $? ]]; then
+  [[ -n $FUNL_DEBUG ]] && echo "funl-select: failed in funl-config: $1: $src" >&2
   exit 1
 fi
 
 # TODO: Support both peco and percol (self-modifying for speed?)
 selected=$(eval "$src | peco" 2>&1)
 if [[ 0 -ne $? ]]; then
+  [[ -n $FUNL_DEBUG ]] && echo "funl-select: failed in 'src' or peco" >&2
   exit 1
 fi
 
